# Generated by Django 5.1 on 2024-08-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzum_copy', '0004_remove_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
    ]
